joust :project4.cpp knight.o weapon.o
	g++ project4.cpp knight.o weapon.o -o joust

knight.o: knight.cpp knight.h weapon.h
	g++ knight.cpp -c

weapon.o: weapon.cpp weapon.h
	g++ weapon.cpp -c
